datasets:
  - json_path: DATAS/LLaVA_Video/basketball_qa_train_100k.json
    sampling_strategy: "first:50000"
  - json_path: DATAS/LLaVA_Video/basketball_caption_train_100k.json
    sampling_strategy: "first:50000"
  - json_path: DATAS/LLaVA_Video/soccer_qa_train_100k.json
    sampling_strategy: "first:50000"
  - json_path: DATAS/LLaVA_Video/soccer_caption_train_80k.json
    sampling_strategy: "first:50000"
  - json_path: DATAS/LLaVA_Video/hockey_qa_train_100k.json
    sampling_strategy: "first:50000"
  - json_path: DATAS/LLaVA_Video/hockey_caption_train_100k.json
    sampling_strategy: "first:50000"